name: Daily SSH Connection and Command

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  ssh_command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute SSH commands
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: s1.ct8.pl
        username: feifan16
        password: Asdqwe123
        port: 22
        script: |
          pm2 list
          sleep 3
          pm2 resurrect
