name: Daily SSH Connection and Command

on:
  schedule:
    - cron: '0 * * * *'  # 每小时触发一次
  workflow_dispatch:

jobs:
  ssh_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Execute remote SSH command
      run: |
        sshpass -p "Asdqwe123" ssh -o StrictHostKeyChecking=no -p 22 feifan16@s1.ct8.pl << EOF
        pm2 list
        sleep 3
        pm2 resurrect
        EOF
